language: python
python: 2.7
sudo: false
cache:
  directories:
    - eggs
env:
  - PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
  - sed -ie "s#test-4#test-$PLONE_VERSION#" buildout.cfg
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout -Nq
before_script:
  - firefox -v
  - export DISPLAY=:99.0
  - export GROK_DISABLE_TEMPLATE_WARNING=on
  - sh -e /etc/init.d/xvfb start
  - cat /etc/init.d/xvfb
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
