language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
- PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
- sed -ie "s#-4.3.x.cfg#-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
- export GROK_DISABLE_TEMPLATE_WARNING=on
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
